sdo: required
services:
  -docker

before_install:
  - docker build -t peterjwhiting/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true peterjwhiting/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-331141108008"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  #test comment test new permissions.



